django/BOARD2/BOARD/BOARD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'))
]

django/BOARD2/BOARD/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('delete/<int:pk>/', views.delete, name="delete"),
    path('update/<int:pk>/', views.update, name="update"),
    path('<int:pk>/create_comment/', views.create_comment)
] 

django/BOARD2/BOARD/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=25)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # on_delete 는 소속된 글이 사라졌을 때 Comment의 자료들은 어떻게 될 것인지? 좋은 관례는 같이 지워지는 것 
    # models.OneToOne()
    # models.ManyToMany()
    

django/BOARD2/BOARD/posts/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import Post, Comment

# Create your views here.

def index(request):
    articles = Post.objects.all()
    context = {
        'articles':articles
    }
    return render(request, 'posts/index.html', context)

def detail(request, pk):
    # pk라는 id를 가진 글을 찾아와 보여줌
    article = Post.objects.get(pk=pk)
    aticles = Post.objects
    # 해당 글에 달려있는 모든 댓글을 보여줌
    comments = article.comment_set.all()
    context = {
        "article":article,
        "comments":comments,
        "article":article,
    }
    return render(request, 'posts/detail.html', context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        content = request.POST.get("content")
        Post.objects.create(title=title, content=content)
        return redirect('posts:index')
    else:
        return render(request, 'posts/create.html')

def delete(request, pk):
    article = get_object_or_404(Post, pk=pk)
    article.delete()
    return redirect('posts:index')

def update(request, pk):
    article = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.save()
        return redirect('posts:index')
    else:
        context = {
            "article":article,
        }
        return render(request, 'posts/update.html', context)

def create_comment(request, pk):
    # 댓글 작성 후, 디테일 페이지로 리다이렉트
    Comment.objects.create(
        content=request.GET.get('content'),
        post=Post.objects.get(pk=pk),
    )
    return redirect('posts:detail', pk)

django/BOARD2/BOARD/BOARD/templates/__footer.html
<footer class="footer mt-auto fixed-bottom bg-light">
  <p class="text-center">Copyright 2019 <a href="https://github.com/MinG822">MinG</a></p>
</footer> 

django/BOARD2/BOARD/BOARD/templates/__navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'posts:index' %}">articles</a>
      <a class="nav-item nav-link" href="{% url 'posts:create' %}">new article</a>
    </div>
  </div>
</nav> 

django/BOARD2/BOARD/BOARD/templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Board Template CRUD</title>
  </head>
  <body>
    {% include '_navbar.html' %}
    {% block body %}

    {% endblock %}
    {% include '_footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body> 

django/BOARD2/BOARD/posts/templates/posts/create.html
{% extends "base.html" %}

{% block body %}
<h1 class="text-center my-5">New Post</h1>
<div class="container">
  <form action="{% url 'posts:create' %}", method="POST">
    <div class="form-group">
      {% csrf_token %}
      <label for="title">title</label>
      <input class="form-control" type="text" id="title" name="title">
      <label for="content">content</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
      <input type="submit" class="btn btn-primary">
    </div>
  </form>
</div>
{% endblock %} 

django/BOARD2/BOARD/posts/templates/posts/detail.html
{% extends "base.html" %}

{% block body %}


<div class="container mt-3">
  <h1>{{ article.title }}</h1>

  <div class="media">
    <div class="media-body">
      <p>{{ article.content }}</p>
    </div>
  </div>
  <div class="d-flex justify-content-between">
    <div class="mb-0">{{ article.updated_at }}</div>
    <div>
      <a href="{% url 'posts:update' article.pk %}">update</a>
      <a href="{% url 'posts:delete' article.pk %}">delete</a>
    </div>
  </div>
  <hr>
</div>

<div class="container">
  <h5>my comment</h5>
  <div>
    <form action="/posts/{{ article.pk }}/create_comment/">
      <div class="form-row">
        <div class="col-10">
          <input class="form-control" type="text" name="content">
        </div>
        <div class="col-2">
          <input type="submit" class="btn btn-primary">
        </div>
      </div>
    </form>
  </div>
  <hr>
  <div>
    <h5>comments</h5>
    <ul class="list-group">
      {% for comment in comments %}
        <li class="list-group-item disabled d-flex justify-content-between">
          <div>{{ comment.content }}</div>
          <div>
            <a href="">update</a>
            <a href="">delete</a>
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

django/BOARD2/BOARD/posts/templates/posts/index.html
{% extends "base.html" %}

{% block body %}

  <h1 class="text-center my-3">BLOG TEMPLATE</h1>
  <div class="d-flex justify-content-center">
    <img src="https://cdn.pixabay.com/photo/2015/06/08/15/11/umbrella-801918_960_720.jpg" alt="arbitrary blog image" style="max-width: 30%">
  </div>
  <h2 class="text-center my-5">Articles</h2>
  <div class="container">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">title</th>
          <th scope="col">created_at</th>
          <th scope="col">updated_at</th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
        <tr>
          <th scope="row">{{ article.id }}</th>
          <td><a href="{% url 'posts:detail' article.id %}">{{ article.title }}</a></td>
          <td>{{ article.created_at }}</td>
          <td>{{ article.updated_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  

{% endblock %}

django/BOARD2/BOARD/posts/templates/posts/update.html
{% extends "base.html" %}

{% block body %}

<div class="container">
  <form action="{% url 'posts:update' article.pk %}", method="POST">
    <div class="form-group">
      {% csrf_token %}
      <label for="title">title</label>
      <input class="form-control" type="text" id="title" name="title" value="{{ article.title }}">
      <label for="content">content</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
      <input type="submit" class="btn btn-primary">
    </div>
  </form>
</div>

{% endblock %} 