django/RECAP_DOWN/RECAP/RECAP/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comment/', views.comment, name='comment'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>', views.comment_delete, name='comment_delete'),
    # 보충수업
    path('<int:article_pk>/comment2/', views.comment2, name='comment2'),
    path('<int:article_pk>/comment2_delete/<int:comment2_pk>', views.comment2_delete, name='comment2_delete'),
    # cookie
    path('send_cookie/', views.send_cookie, name='send_cookie'),
    # add like
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/like2/', views.like2, name='like2'),
    path('explore/', views.explore, name='explore'),
    path('tags/', views.tags, name='tags'),
    path('hashtag/<int:hashtag_pk>', views.Hashtag, name="hashtag")
]

django/RECAP_DOWN/RECAP/RECAP/recap/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<username>/', accounts_views.profile, name='profile'),
]

django/RECAP_DOWN/RECAP/RECAP/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # M:N 관계 형성, 중계필드를 가져와서 원본필드를 바꾸는게 아니니까 makemigrations해서 상관없다.
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pk',)

    # method 추가 예정
    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'article_pk': self.pk})


class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # M:N 관계 형성

    def __str__(self):
        return self.content[:10]
    
    class Meta:
        ordering = ('-pk',)

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'article_pk': article.pk})


# 보충수업
class Comment2(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.content



    

django/RECAP_DOWN/RECAP/RECAP/articles/forms.py
from django import forms
from .models import Article, Comment, Comment2

# # Form Class
# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=20,
#         label='제목',
#         help_text='제목은 20자를 넘길 수 없습니다.',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'form-control my-content',
#                 'placeholder': '제목을 입력해주세요',
#             }
#         )
#         )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'form-control my-content',
#                 'placeholder': '내용을 입력해주세요',
#                 'rows': 5,
#                 'cols': 50,
#             }
#         )
#         )

# modelForm class
class ArticleForm(forms.ModelForm):
    # class Meta:
    #     """
    #     사용할 필드를 명시하는 것이 중요하다.
    #     # exclude = ('title', ...)
    #     # widgets = {
    #     #     '필드': form속성
    #     # }
    #     """
    #     model = Article
    #     fields = ('title', 'content',)

    #     widgets = {
    #         'title': forms.TextInput(attrs={
    #             'placeholder': '제목을 입력해주세요.',
    #             'class': 'form-control my-content',
    #             'id': 'title'
    #         })
    #     }
    
    # 필드를 커스텀하여 관리하기 편한 방식: 장고에서는 이러한 것을 추천한다.

    class Meta:
        model = Article
        fields = ('title', 'content',)


    title = forms.CharField(
        max_length=20,
        label='제목',
        help_text='제목은 20자를 넘길 수 없습니다.',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control my-content',
                'placeholder': '제목을 입력해주세요',
            }
        )
    )

    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control my-content',
                'placeholder': '내용을 입력해주세요',
                'rows': 5,
                'cols': 50,
            }
        )
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    
    content = forms.CharField(
        max_length=300,
        label='댓글',
    )
    # article = forms.ModelChoiceField(queryset=Article.objects.all())




# 보충수업
class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment2
        fields = ('content',)

django/RECAP_DOWN/RECAP/RECAP/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_or_create
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentModelForm, CommentForm
from IPython import embed
from django.http import Http404, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from itertools import chain

# Create your views here.
@login_required
def index(request):
    # embed()
    # 세션 조작을 통해 방문수 카운트
    visits_num = request.session.get('visits', 0)
    request.session['visits'] = visits_num + 1
    request.session.modifided = True
    followings = request.user.followings.all()
    # 방법 1
    followings = chain(followings, [request.user])
    articles = Article.objects.filter(user__in=followings)

    context = {
        'articles': articles,
        'visits': visits_num,
    }
    return render(request, 'articles/index.html', context)

"""
# 보충수업용 commentout
def detail(request, article_pk):
    # article = get_object_or_404(Article, pk=article_pk)
    
    # article = Article.objects.get(pk=article_pk)

    # getobjector404
    try:
        article = Article.objects.get(pk=article_pk)
    except Article.DoesNotExist:
        raise Http404('해당하는 글이 없습니다.')

    form = CommentForm()

    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/detail.html', context)
"""

def detail(request, article_pk):
    # article = get_object_or_404(Article, pk=article_pk)

    # article = Article.objects.get(pk=article_pk)

    # getobjector404
    try:
        article = Article.objects.get(pk=article_pk)
    except Article.DoesNotExist:
        raise Http404('해당하는 글이 없습니다.')

    comment_form = CommentForm()

    # 보충수업
    # 명시적으로 commentForm 분리
    comment2_form = CommentModelForm()

    context = {
        'article': article,
        'comment2_form': comment2_form,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    """
    # user 로그인되어있는지 여부를 확인
    if request.user.is_anonymous:
        return redirect('accounts:login')
    """
    if request.method == 'POST':
        # embed()
        # 이 코드는 아래 코드로 대체
        # title = request.POST.get('title')
        # content = request.POST.get('content')        
        # new_article = Article.objects.create(title=title, content=content)

        form = ArticleForm(request.POST)
        
        # 전송된 데이터가 유효한지 검사
        if form.is_valid():
            # Using Form
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # article = Article.objects.create(title=title, content=content)

            # # using modelForm
            # article = form.save()

            # using user_id
            article = form.save(commit=False)
            article.user = request.user
            article.save()

            #hashtag
            for word in article.content.split():
                if word.startswith('#'):
                    hashtag, created = Hashtag.objects.get_or_create(content=word)
                    #return 값이 (객체, T/F)
                    article.hastags.add(hashtag)
        # form.save()도 가능하지만 일단 데이터 클렌징 먼저 시행한다.

            return redirect(article)
        else:
            return redirect('articles:create')
    else:
        form = ArticleForm()
        context = {
            'form': form,
        }
        return render(request, 'articles/create.html', context)

# UPDATE => articles/:id/update | (PUT) articles/:id (REST)
# DELETE => articles/:id/delete

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    """
    추가: article을 수정하려는 유저가 접속한 유저와 같을 경우에만 등록
    """
    if article.user == request.user:
        if request.method == 'POST':
            # form = ArticleForm
            embed()
            # 만약 ArticleForm에 인자를 하나 넘겨주면 생성, instance 인자를 함께 넘겨주면 수정
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect(article)
                # using Form
                # article.title = form.cleaned_data.get('title')
                # article.content = form.cleaned_data.get('content')
                # article.save()

                # using modelForm
                # article = form.save()
                # return redirect(article)
    
        form = ArticleForm(instance=article)
        context = {
            'article': article,
            'form': form,
        }

        # article = Article.objects.get(pk=article_pk)
        # form = ArticleForm(initial={
        #     'title': article.title,
        #     'content': article.content,
        # })
        # context = {
        #     'article': article,
        #     'form': form,
        # }
        
        return render(request, 'articles/update.html', context)
    else:
        return redirect(article)

# make decorators for delete function
@login_required
@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    """
    추가: article을 수정하려는 유저가 접속한 유저와 같을 경우에만 삭제
    """
    if article.user == request.user:
        if request.method == 'POST':
            article.delete()
            return redirect('articles:index')
        else:
            return redirect(article)
    else:
        return redirect(article)

"""
# custom error(401 Error: Unauthorized User Error)
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.method == 'POST':
            article.delete()
            return redirect('articles:index')
        else:
            return redirect(article)

    return HttpResponse('검증되지 않은 유저입니다.', status=401)
"""

def comment(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
    
    return redirect(article)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if request.method == 'POST':
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()
    
    return redirect("articles:detail", article_pk=article_pk)

# 보충수업
def comment2(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    if request.method == 'POST':
        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)# commit == database commit, 실제 데이터베이스에 저장하는 과정
            embed()

            # 방법1
            comment.article_id = article_pk

            comment.save()

            # 객체를 직접 넣는것도 가능
            # comment.article = Article.objects.get(pk=article_pk)
    
    return redirect(article)


def comment2_delete(request, article_pk, comment_pk):
    pass


def send_cookie(request):
    """
    현재까지 return했던 것
    render(), redirect(), reverse(), HttpResponse()
    """

    res = HttpResponse('과자보냅니다')
    res.set_cookie('mycookie', 'oreo')
    return res


# like 기능
@login_required
def like(request, article_pk):
    # article_pk를 user가 좋아하는 것을 추가
    article = get_object_or_404(Article, pk=article_pk)
    # article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    """
    # 방법 1
    request.user.like_articles.add(Articles.objects.get(pk=article_pk))
    """
    """
    # 방법2 
    request.user.like_articles.add(article)
    """
    """
    # 방법 3
    else:
        article.like_users.add(request.user)
    """

    return redirect(article)

@login_required
@require_POST
def like2(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    # embed()
    """
    try:
        article.like_users.get(pk=user.pk)
        article.like_users.remove(request.user)
    except:
        article.like_users.add(request.user)
    """

    # 다른 방법
    if article.like_users.filter(pk=user.pk).exists(): # SQL-WHERE과 같은 역할을 한다.
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    
    """
    .get()의 경우 하나의 객체만 리턴한다.
    .filter()의 경우 여러 객체에 대한 queryset을 리턴한다.
    단, .get()보다는 .filter()를 쓰는 것이 좋은 이유는 없을 경우에 대한 error handling의 용이성때문이다.
    만약 찾는 객체가 없을 경우 .get()은 None을 리턴하여 에러를 발생시키지만, .filter()는 빈 쿼리셋을 리턴하기 때문에 

    """

    return redirect(article)


def explore(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/explore.html', context)

def tags(request):
    tags = Hashtag.objects.all()
    context = {
        'tags' : tags,
    }
    return render(request, 'articles/tags.html', context)

def hashtag(request, hashtag_pk):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_pk)
    articles = hashtag.article_set.all()
    context = {
        'hashtag': hashtag,
        'articles':articles,
    }
    return render(request, 'articles/hashtags.html', context)

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<h1 id="title">새 글 쓰기</h1>
<form action="/articles/create/" method="POST">
{% csrf_token %}
<input type="text" name="title">
<input type="text" name="content">
<button type="submit">submit</button>
</form>


<h1>Form class로 html form 생성</h1>
<form action="/articles/create/" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit">submit</button>
</form>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="mt-3 d-flex justify-content-between">
  <div class="d-inline-block ml-3">
    <p class="d-inline-block my-1" style="font-weight: 300;"><small>작성자</small>{{ article.user }} |
      {{ article.user.first_name }} | </p>
    <p class="d-inline-block my-1" style="font-weight: 300;">{{ article.pk }} | </p>
    <p class="d-inline-block my-1" style="font-weight: 400;">{{ article.title }}</p>
  </div>
  <div class="d-inline-block mr-3">
    <p class="d-inline-block my-1" style="font-weight: 300;">작성일시:
      {{ article.created_at|date:"SHORT_DATETIME_FORMAT" }}</p>
  </div>
</div>

<hr>

<div class="px-3">
  <p>{{ article.content }}</p>
</div>

{% if article.user == user %}
{% if user.is_authenticated %}
<a href="{% url 'articles:update' article.pk %}">
  <button class="btn btn-sm btn-outline-dark">update</button>
</a>
<form class="d-inline-block form-inline my-0" action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button class="btn btn-sm btn-outline-danger" type="submit">delete</button>
</form>
{% endif %}
{% endif %}

<hr>

{% comment %}

<p>comment1</p>
<form action="{% url 'articles:comment' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form %}
  <input type="submit" value="submit">
</form>

<p>comment2</p>
<form action="{% url 'articles:comment2' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment2_form %}
  <input type="submit" value="submit">
</form>

{% endcomment %}

<p>해시태그목록</p>
<p><strong>
  {% for hashtag in article.hashtags.all %}
    {{ hashtags }}
  {% endfor %}
</strong></p>

{# 좋아요 목록 #}
{# <a href="/articles/:id/like/:article"></a> #}
{#{% if user.is_authenticated and user in article.like_users.all %}#}

{% with likeusers=article.like_users.all %}
    {% if user.is_authenticated and user in likeusers %}
      <form class="m-0 form-inline d-inline-block" action="{% url 'articles:like2' article.pk %}" method="POST" id="like">
        <a style="cursor: pointer;" onclick="document.getElementById('like').submit();">
        <div class="d-inline-block" style="z-index:10; background-size: 218%; height: 20px;width: 20px;background-position: -22px -12px; background-image:url({% static 'like.jpg' %})"></div>
    {% else %}
      <form class="m-0 form-inline d-inline-block" action="{% url 'articles:like2' article.pk %}" method="POST" id="like">
        <a style="cursor: pointer;" onclick="document.getElementById('like').submit();">
        <div class="d-inline-block" style="background-size: 218%;height: 20px; width: 20px;background-position: -3px -12px; background-image:url({% static 'like.jpg' %})"></div>
    {% endif %}
        </a>
        {% csrf_token %}
      </form>
  <p class="d-inline-block">{{ article.like_users.count }} 개의 좋아요</p>
  <p>
    {% for likeuser in likeusers %}
      <span>{{ likeuser.username }}</span>
    {% endfor %}
    가 이 글을 좋아합니다.
  </p>
{% endwith %}

댓글 갯수 {{ article.comment_set.all|length }}

<hr>


<div>
  <form class="d-inline-block" action="{% url 'articles:comment' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="text" name="content" id="content">
    <button type="submit">submit</button>
  </form>
</div>
<div>
  {% if article.comment_set.all %}
  <!-- 템플릿 데이터를  -->
  <h2>댓글목록</h2>
  {% for comment in article.comment_set.all %}
  <div>
    <p class="d-inline-block my-1">
      <span style="font-weight:300">{{ forloop.revcounter }} | <small>작성자</small> {{ comment.user }} |
      </span><span style="font-weight:400">{{ comment.content }}</span>
    </p>
    <form class="d-inline-block form-inline my-1" action="{% url 'articles:comment_delete' article.pk comment.pk %}"
      method="post" id="comment_delete{{ comment.pk }}">
      {% csrf_token %}
      <a onclick="document.getElementById('comment_delete{{ comment.pk }}').submit();">
        <button class="btn btn-sm btn-outline-danger py-0"
          style="vertical-align: unset;height:20px;">delete</button></a>
    </form>
  </div>
  {% endfor %}
  {% else %}
  <p>댓글을 등록해주세요.</p>
  {% endif %}
</div>





{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/explore.html
{% extends 'base.html' %}

{% block body %}

{% for article in articles %}
  <p>{{ article.title }}</p>
  <p>{{ article.user }}</p>
  <a href="{% url 'articles:detail' article.pk %}">상세보기</a>
{% endfor %}

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/hashtag.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ hashtag.content }}</h1>

<ul>
{% for article in articles %}
  <li>제목 : {{ article.title }}</li>
  <li>내용 : {{ article.content }}</li>
  <li>좋아요 : {{ article.like_users.count }}</li>
  <li>댓글 : {{ article.comment_set.count }}</li>
{% endfor %}
</ul>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
{{ visits }}

<h1 id="title">Articles</h1>
<!-- show all articles -->

<table class="table table-hover">
    <thead>
        <td>pk</td>
        <td colspan="3">title</td>
        <td>date</td>
    </thead>
{% for article in articles %}
<tr>
    <td>{{ article.pk }}</td>
    <td colspan="3"><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
    <td>{{ article.created_at|date:"Y-m-j" }}</td>
</tr>
{% endfor %}
</table>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/tags.html
{% extends 'base.html' %}

{% block body %}

<h1>태그모음</h1>
{% for tag in tags %}
  <a href="{% url 'articles:hashtag' tag.pk %}">{{ tag }}</a>
{% endfor %}

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<h1>Form class로 html form 수정</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit">submit</button>
</form>


{% endblock %}