django/RECAP_DOWN/RECAP/RECAP/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:person_pk>/', views.follow, name='follow')
]

django/RECAP_DOWN/RECAP/RECAP/recap/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<username>/', accounts_views.profile, name='profile'),
]

django/RECAP_DOWN/RECAP/RECAP/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

django/RECAP_DOWN/RECAP/RECAP/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # M:N 관계 형성, 중계필드를 가져와서 원본필드를 바꾸는게 아니니까 makemigrations해서 상관없다.
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pk',)

    # method 추가 예정
    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'article_pk': self.pk})


class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # M:N 관계 형성

    def __str__(self):
        return self.content[:10]
    
    class Meta:
        ordering = ('-pk',)

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'article_pk': article.pk})


# 보충수업
class Comment2(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.content



    

django/RECAP_DOWN/RECAP/RECAP/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)

# class CustomPasswordChangeForm(PasswordChangeForm):

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

django/RECAP_DOWN/RECAP/RECAP/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST
from IPython import embed
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model


# Create your views here.
def signup(request):
    # embed()
    if request.method == 'POST':
        # 보내온 정보 저장
        # embed()

        """
        # 검증 먼저
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('aritcles:index')
        """

        # 검증 먼저
        form = CustomUserCreationForm(request.POST)
        # embed()
        if form.is_valid():
            form.save()
            return redirect('articles:index')
        
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # embed()
        """logic 흐름
        username이 username인 것을 찾고
            if form.is_valid():
                username = request.POST.get('username')
                user = User.objects.get(username=username)
                if user:
                    if user.password == request.POST.get('password'):
                        # 로그인 시킨다: 세선 생성한다.
                else:
                    # 사용자가 없다.
        """
        
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)

def logout(request):
    # 세선에서 유저 정보 지우기 / 세션 지우기
    auth_logout(request)

    return redirect('articles:index')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('accounts:signup')
    # pass

@login_required
def update(request):
    if request.method == 'POST':
        # 변경사항 업데이트
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        # 폼 보여주기
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        # 비밀번호 변경
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            # session auth hash를 변경
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        # 폼 보여주기
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)

def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person, 
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, person_pk):
    person = get_object_or_404(get_user_model(), pk=person_pk)
    user = request.user
    
    user.followers.add(person)


    return redirect('profile', username=person.username)

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/_change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<!-- change PW -->
<h1>change password</h1>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="제출" %}
    {% endbuttons %}
</form>

<hr>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/_login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<!-- user form 사용 -->
<h1>로그인</h1>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="로그인" %}
    {% endbuttons %}
</form>

<hr>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/_signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<!-- 지난주 이전까지는 이렇게 했을 것이다 -->
<h1>회원가입</h1>

<form action="#" method="post">
    {% csrf_token %}
    <input type="text" name="" id="">
    <input type="text" name="" id="">
    <button type="submit">등록하기</button>
</form>

{{form.as_p}}

<hr>

<!-- user form 사용 -->
<h1>회원가입</h1>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="회원가입" %}
    {% endbuttons %}
</form>

<hr>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<!-- login -->
<h1>update</h1>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="업데이트" %}
    {% endbuttons %}
</form>

<hr>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<!-- change PW -->
{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
<h1>회원정보 변경</h1>
{% else %}
<h1>비밀번호 변경</h1>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="제출" %}
    {% endbuttons %}
</form>

<hr>

{% endblock %}

django/RECAP_DOWN/RECAP/RECAP/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}


<h1>{{ person.username }}</h1>
{% with followers=person.followers.all followings=person.followings.all %}
  {% if user != person %}
    {% if in followers %}
    <a class="btn btn-outline-primary" href="/accounts/follow/{{ person.pk }}" class="btn btn-primary">언팔로우</a>
    {% else %}
    <a class="btn btn-primary" href="/accounts/follow/{{ person.pk }}" class="btn btn-primary">팔로우</a>
    {% endif %}
  {% endif %}
  <p>팔로워수 : {{ followers|length }}</p> 
  <p>팔로워들 :
    {% for follower in person.followers.all %}
      {{ follower }}
    {% endfor %}</p> 
  <p>팔로잉수 : {{ followings|length }}</p> 
  <p>팔로워들 :
    {% for following in followings %}
      {{ following }}
    {% endfor %}</p> 
{% endwith %}

{% with articles=person.article_set.all %}
  {% for article in articles %}
    <p>{{ article.pk }} | {{ article.title }} | 좋아요 {{ article.like_users.count }} | 댓글 {{ article.comment_set.count }}</p>
  {% endfor %}
{% endwith %}


{% with likearticles=person.like_articles.all %}
  {% for likearticle in likearticles %}
    {{ likearticle }}
  {% endfor %}
{% endwith %}

{% endblock %}